### ISSUE TITLE
Assertion triggered in Mac::HandleTransmitDone() in rare cases (cloud stress test)

### ISSUE THREAD

**Issue by EskoDijk** [EskoDijk/ot-ns#27]
```
023-06-01 19:53:19,729 - INFO - OTNS >>> node=1    dst=fdde:ad00:beef:0:486c:2262:6b9:1907      datasize=32  delay=0.000ms
2023-06-01 19:53:19,729 - INFO - OTNS >>> node=45   dst=fdde:ad00:beef:0:486c:2262:6b9:1907      datasize=32  delay=236.080ms
2023-06-01 19:53:19,729 - INFO - OTNS >>> Done
2023-06-01 19:53:19,729 - INFO - OTNS <<< move 24 592 227
2023-06-01 19:53:19,729 - INFO - OTNS >>> Done
2023-06-01 19:53:19,729 - INFO - OTNS <<< move 25 288 617
2023-06-01 19:53:19,730 - INFO - OTNS >>> Done
2023-06-01 19:53:19,730 - INFO - OTNS <<< move 40 27 209
2023-06-01 19:53:19,730 - INFO - OTNS >>> Done
2023-06-01 19:53:19,730 - INFO - OTNS <<< move 37 765 662
2023-06-01 19:53:19,730 - INFO - OTNS >>> Done
2023-06-01 19:53:19,730 - INFO - OTNS <<< move 11 386 733
2023-06-01 19:53:19,730 - INFO - OTNS >>> Done
2023-06-01 19:53:19,730 - INFO - OTNS <<< go 60
error	2023-06-01 19:53:21.881 - Node 9 process failed: ot-cli-ftd: /home/runner/work/ot-ns/ot-ns/ot-rfsim/openthread/src/core/mac/mac.cpp:1447: void ot::Mac::Mac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed.
warn	2023-06-01 19:53:26.643 - syncing 1 alive nodes: map[9:{}]
info	2023-06-01 19:53:26.643 - Deleting node 9 due to process failure.
2023-06-01 19:53:36,422 - INFO - OTNS >>> Error: ot-cli-ftd: /home/runner/work/ot-ns/ot-ns/ot-rfsim/openthread/src/core/mac/mac.cpp:1447: void ot::Mac::Mac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed.
Traceback (most recent call last):
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/BaseStressTest.py", line 52, in run_wrapper
    orig_run(self)
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/mleid_connectivity.py", line 123, in run
    ns.go(MOVE_INTERVAL)
  File "/home/runner/.local/lib/python3.7/site-packages/pyOTNS-0.0.0-py3.7.egg/otns/cli/OTNS.py", line 98, in go
    self._do_command(cmd)
  File "/home/runner/.local/lib/python3.7/site-packages/pyOTNS-0.0.0-py3.7.egg/otns/cli/OTNS.py", line 216, in _do_command
    raise OTNSCliError(line[7:])
otns.cli.errors.OTNSCliError: ot-cli-ftd: /home/runner/work/ot-ns/ot-ns/ot-rfsim/openthread/src/core/mac/mac.cpp:1447: void ot::Mac::Mac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed.
2023-06-01 19:53:36,423 - INFO - waiting for OTNS to close ...
info	2023-06-01 19:53:36.423 - program exit: <nil>
info	2023-06-01 19:53:36.423 - stopping simulation and exiting nodes ...
info	2023-06-01 19:53:36.449 - program context waiting routines: map[dispatcher:0 grpcwebproxy:0 handleSignals:0 simulation:1]
Traceback (most recent call last):
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/run_stress_suite.py", line 95, in <module>
    main()
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/run_stress_suite.py", line 70, in main
    run_suite(script_dir, suite_name)
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/run_stress_suite.py", line 91, in run_suite
    t.run(report=True)
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/BaseStressTest.py", line 60, in run_wrapper
    self.report()
  File "/home/runner/work/ot-ns/ot-ns/pylibs/stress_tests/BaseStressTest.py", line 120, in report
    raise RuntimeError("Stress test failed: \n" + "\n".join("\t" + msg for msg in self.result._fail_msgs))
RuntimeError: Stress test failed: 
Error: 	ot-cli-ftd: /home/runner/work/ot-ns/ot-ns/ot-rfsim/openthread/src/core/mac/mac.cpp:1447: void ot::Mac::Mac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed.
**[OTNS](https://github.com/openthread/ot-ns) Stress Tests Report Generated at 06/01 19:53:36**
#### ML-EID Connectivity Test **Failed**: ot-cli-ftd: /home/runner/work/ot-ns/ot-ns/ot-rfsim/openthread/src/core/mac/mac.cpp:1447: void ot::Mac::Mac::HandleTransmitDone(ot::Mac::TxFrame&, ot::Mac::RxFrame*, ot::Error): Assertion `false' failed. _(06/01 19:36:06 ~ 06/01 19:53:36)_
| Simulation Time | Max Delay | Min Delay | Avg Delay |
| :-: | :-: | :-: | :-: |
Error: Process completed with exit code 1.
```

**Comment by EskoDijk** [comment]
Closing, not recently observed.
