### ISSUE TITLE
If the only node crashes, simulation panics (index error)

### ISSUE THREAD

**Issue by EskoDijk** [EskoDijk/ot-ns#31]
```
debug	2023-06-03 21:06:06.397 - simulation exit.
panic: runtime error: slice bounds out of range [:-1]

goroutine 68 [running]:
github.com/openthread/ot-ns/simulation.(*Node).Command(0xc000436b40, {0xab474e, 0x11}, 0xc00032e660?)
	/home/esko/ot-ns/simulation/node.go:223 +0x13e
github.com/openthread/ot-ns/simulation.(*Node).RunInitScript(0xc000436b40?, {0xfe92e0, 0x6, 0x0?})
	/home/esko/ot-ns/simulation/node.go:151 +0xac
github.com/openthread/ot-ns/simulation.(*Simulation).AddNode(0xc0001e3b80, 0xc00099f4a0)
	/home/esko/ot-ns/simulation/simulation.go:144 +0x3e5
github.com/openthread/ot-ns/cli.(*CmdRunner).executeAddNode.func1(0xc0003ae420?)
	/home/esko/ot-ns/cli/CmdRunner.go:369 +0x2a
github.com/openthread/ot-ns/cli.(*CmdRunner).postAsyncWait.func1()
	/home/esko/ot-ns/cli/CmdRunner.go:306 +0x2d
github.com/openthread/ot-ns/dispatcher.(*Dispatcher).Run(0xc000150000)
	/home/esko/ot-ns/dispatcher/dispatcher.go:294 +0x2e4
github.com/openthread/ot-ns/simulation.(*Simulation).Run(0xc0001e3b80)
	/home/esko/ot-ns/simulation/simulation.go:169 +0x105
created by github.com/openthread/ot-ns/otns_main.Main
	/home/esko/ot-ns/otns_main/otns_main.go:186 +0x41b
```

**Comment by EskoDijk** [comment]
more error handling added in node.go in #32
